import argparse
import json
from pathlib import Path
from typing import List, Optional

from app.sim.agents import (
    Design,
    ListingResult,
    trend_agent,
    prompt_agent,
    image_agent,
    compliance_agent,
    mockup_agent,
    pricing_agent,
    listing_simulator,
    to_serializable,
)
from app.sim.manager import ManagerAgent
from app.sim.utils import save_json, timestamp, DATA_DIR

DEFAULT_NICHES = [
    "cozy autumn",
    "pet lovers",
    "minimalist motivation",
    "retro outdoors",
    "bookish humor",
    "coffee culture",
]
DEFAULT_PRODUCT_TYPES = ("mug", "tshirt", "tote")
DEFAULT_MARGIN = 0.42

ETSY_CONFIG_PATH = DATA_DIR / "etsy_config.json"


def load_etsy_config() -> dict:
    if not ETSY_CONFIG_PATH.exists():
        raise SystemExit(
            f"--etsy-mode requires {ETSY_CONFIG_PATH} to exist. Run:\n"
            "    python -m app.setup.etsy_wizard\n"
            "first to generate it."
        )
    with open(ETSY_CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def apply_etsy_fees(designs: List[Design], results: List[ListingResult], fees: dict) -> None:
    """Deducts Etsy's real fee structure from each result's profit, in place:
    - listing_fee: charged once per listing that actually went live (approved)
    - transaction_fee_pct: percent of revenue, charged on sales
    - payment_fee_pct / payment_fee_flat: payment processing, charged per order
    """
    listing_fee = fees.get("listing_fee", 0.0)
    transaction_fee_pct = fees.get("transaction_fee_pct", 0.0) / 100.0
    payment_fee_pct = fees.get("payment_fee_pct", 0.0) / 100.0
    payment_fee_flat = fees.get("payment_fee_flat", 0.0)

    by_id = {d.design_id: d for d in designs}
    for r in results:
        design = by_id.get(r.design_id)
        if not design or not design.approved:
            continue
        transaction_fee = r.revenue * transaction_fee_pct
        payment_fee = (r.revenue * payment_fee_pct) + (r.orders * payment_fee_flat)
        total_fees = listing_fee + transaction_fee + payment_fee
        r.profit = round(r.profit - total_fees, 2)


def run_once(etsy_mode: bool = False) -> str:
    niches = DEFAULT_NICHES
    product_types = DEFAULT_PRODUCT_TYPES
    target_margin = DEFAULT_MARGIN
    etsy_config: Optional[dict] = None

    if etsy_mode:
        etsy_config = load_etsy_config()
        niches = etsy_config.get("niches") or niches
        product_types = tuple(etsy_config.get("product_types") or product_types)
        target_margin = etsy_config.get("target_margin", target_margin)

    manager = ManagerAgent()

    designs = trend_agent(niches=niches, k=24)
    designs = manager.review_trends(designs)

    prompt_agent(designs)
    image_agent(designs)
    compliance_agent(designs)
    manager.review_compliance(designs, recheck=compliance_agent)

    mockup_agent(designs, product_types=product_types)
    pricing_agent(designs, target_margin=target_margin)
    manager.review_pricing(designs)
    manager.score_and_decide(designs)  # GREENLIGHT / HOLD / BLOCK + batch status

    results = listing_simulator(designs)
    if etsy_mode and etsy_config:
        apply_etsy_fees(designs, results, etsy_config.get("fees", {}))

    payload = to_serializable(designs, results)
    payload["manager"] = manager.report(designs, results)
    if etsy_mode:
        payload["etsy_mode"] = True
        payload["etsy_config"] = etsy_config

    path = save_json(payload, f"run_{timestamp()}.json")
    return str(path)


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Run one AI POD agent simulation batch.")
    p.add_argument(
        "--etsy-mode",
        action="store_true",
        help=(
            "Use data/etsy_config.json (generated by `python -m app.setup.etsy_wizard`) "
            "for niches/product types/margin, and deduct real Etsy fees "
            "(listing, transaction, payment processing) from profit. Still a "
            "fully simulated run — no real API calls."
        ),
    )
    return p


if __name__ == "__main__":
    args = build_arg_parser().parse_args()
    p = run_once(etsy_mode=args.etsy_mode)
    print(f"Simulation complete. Output: {p}")
